---
title: "Alltrials_trt"
author: "Liz Muntean"
date: "2/25/2021"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r, echo = FALSE}
bcgrowth<-read.csv("./bcsaltgrowthdata24Mar21.xlsx.csv")
Strain=as.factor(bcgrowth$Strain)
bcgrowth<-subset(bcgrowth, bcgrowth$status.at.harvest !="dead")
mass_sum<-bcgrowth%>% select(Strain,salttrt,endotrt,net.change.in.weight) 

```

```{r ggplot}
ggplot(data=mass_sum)+
 aes(x=salttrt, y=net.change.in.weight)+
  geom_boxplot(aes(fill=endotrt,color=endotrt))+
  scale_color_manual(values=c("black","black"))+
  scale_fill_manual(values=c("blue","orange"))+
  facet_wrap(~Strain)
```


```{r}
height_sum<-bcgrowth %>% select(Strain,salttrt,endotrt,net.change.in.height)
Strain=as.factor(height_sum$Strain)

ggplot(data=height_sum)+
 aes(x=salttrt, y=net.change.in.height)+
  geom_boxplot(aes(fill=endotrt,color=endotrt))+
  scale_color_manual(values=c("black","black"))+
  scale_fill_manual(values=c("blue","orange"))+
  facet_wrap(~Strain)
```

